spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3366/house?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: house
    password: house
  batch:
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2
